### ISSUE TITLE
Looking for an accountability partner

### ISSUE THREAD

**Issue by Samy-33** [CosecSecCot/dotfiles#1]
Hey, I watched your streams about practising problem solving on codeforces. I have recently re-started CP as well after a gap of around 5 years. Would be super cool to have an accountability partner. We could teach each other approaches and algorithms.

I find working alone a bit too boring. Let me know if you'll be up for an accountability partnership.

**Comment by CosecSecCot** [comment]
Sure man, you can join my discord server https://discord.gg/Fu52nWCR
